### ISSUE TITLE
Add tests for Spinner component

### ISSUE THREAD

**Issue by matheusps** [matheusps/adapt-ui#48]
The tests should check if:
- The component renders without crashing
- The component renders correctly for all gaps
- The component renders correctly for all thickness
- The component renders correctly for all gaps
- The component renders correctly for all speeds

**Comment by fedebabrauskas** [comment]
Can I be assigned for this one?

**Comment by fedebabrauskas** [comment]
Can I be assigned for this one too?

Thank you.

---

EDIT:
- I opened a PR about this issue, check it below 😄 
- Please ignore the previous reference, it was a mistake.

**Comment by matheusps** [comment]
No problem, assigned to you 🙂
